<html>
<head>
    <title>We're pretty busy!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="refresh" content="15"/>
    <style>
        .metrics {
            color: #F24F4A;
            font-size: 1.5em;
            border: 1px solid #C0C0C0;
        }

        .metrics span {
            font-size: 60%;
            color: #888;
        }

        .block {
            display: block;
        }
    </style>
</head>
<body class="bg-light">

<div class="container-fluid w-100 bg-white py-5 mt-sm-5">
    <div class="row justify-content-center align-items-center">
        <div class="row justify-content-center">
            <div class="col-10 col-md-6">
                <h1>We are pretty busy!</h1>
                <p>Our site is pretty busy right now, but please hold on and you'll get in soon. This page will refresh
                    automatically, keep this page open or you may lose your slot.</p>
                <div class="card mt-5">
                    <div class="row my-3 px-5 text-center">
                        <div class="col-12 col-sm-6">
                            <span class="block">Position</span>
                            {{queue.position}} <span>/ {{queue.total}}</span>
                        </div>
                        <div class="col-12 col-sm-6">
                            <span class="block">ETA</span>
                            {{queue.eta}} <span> minutes</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var wcIsGtm = false;
    var productImpressions = [];
    var promoImpressions = [];
    var wcGuaTrackerName = '';

    (function (w, e, b, c, oo, ki, ng) {
        w['GoogleAnalyticsObject'] = oo;
        w[oo] = w[oo] || function () {
            (w[oo].q = w[oo].q || []).push(arguments)
        }, w[oo].l = 1 * new Date();
        ki = e.createElement(b),
            ng = e.getElementsByTagName(b)[0];
        ki.async = 1;
        ki.src = c;
        ng.parentNode.insertBefore(ki, ng)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', '{{ga_code}}', 'auto');
    ga('set', 'page', 'Queue');
    ga('send', 'pageview');
</script>
</body>
</html>